// <auto-generated />
namespace Aplicacao_RESTful.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Adiciona_Tarefas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Adiciona_Tarefas));
        
        string IMigrationMetadata.Id
        {
            get { return "201609090411018_Adiciona_Tarefas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
